version: "3.7"
services:
  mongodb.mangrove.local:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
    volumes:
      - mangrove_mongodb:/data/db
volumes:
  mangrove_mongodb:
